### ISSUE TITLE
Is https://api.meqa.io/ unavailable?

### ISSUE THREAD

**Issue by eterekhin** [meqaio/swagger_meqa#13]
Hello, I get ERR_CONNECTION_TIMED_OUT when try to open https://api.meqa.io/. 
Is this site unavailable? 

![image](https://user-images.githubusercontent.com/48148702/82122080-0bfb5580-979a-11ea-90c1-8841dd3966a1.png)

Also, I get error with message  "got an err: unexpected and of JSON input" when I try to execute the script 

```./mqgo_windows_amd64.exe generate -d ./ -s ./swagger.yaml```

I use exe file from the last release version of mqgo_windows_amd64.zip. swagger.yaml is petstore swagger specification, so I believe there is no error on my side.

Could you answer is this project still working?

**Comment by yingxie3** [comment]
No I'm not hosting is anymore.
