### ISSUE TITLE
Running everything locally with Docker fails

### ISSUE THREAD

**Issue by fkromer** [meqaio/swagger_meqa#2]
I try to generate the test data from the Open API spec file `/static/api/api_v1.yml` like described in the [docs (run everything locally with Docker)](https://github.com/meqaio/swagger_meqa/tree/master/docs#run-locally). The first command execution seems to be ok (I ignored the UdevQt stuff...). But during the second command execution it fails.

```
❯ docker run --rm -v $PWD/testdata:/testdata -v $PWD/static/api:/static/api meqa/tag mqtag -i /static/api/api_v1.yml -o /testdata/api_v1_meqa.yml
Failed to load file /static/api/api_v1.yml
UdevQt: unhandled device action "move"
❯ docker run --rm -v $PWD/testdata:/testdata meqa/go mqgen -d /testdata -s /testdata/api_v1_meqa.yml 
2018/03/13 15:13:52.068075 parser.go:147: invalid yaml in file /testdata/api_v1_meqa.yml types don't match expect map key string or int got: bool
2018/03/13 15:13:52.068148 main.go:60: Error: types don't match expect map key string or int got: bool
UdevQt: unhandled device action "move"
```

The file `/static/api/api_v1.yml` is valid Open API v2.0. What could be the root cause for this?

**Comment by yingxie3** [comment]
We don't support OpenAPI v2 yet.

**Comment by fkromer** [comment]
Ok.
